"""Higress sink:把统一 Route 渲染为标准 Ingress,投递给 Higress standalone。

三通道(按 cfg.channel):
  dockercp — 渲染 yaml 后 docker cp 进 all-in-one 容器 /data/{ingresses,services,endpoints}/
             (旧 scg-to-higress 项目已验证 standalone api-server watch 该目录)
  kubectl  — 用容器 kubeconfig apply 到内嵌 api-server(:18443)
  console  — TODO 阶段二:登录 console 走 /v1/routes REST

method 级路由:当前 Higress 版本标准 Ingress 不直接支持,首期不限 method(文档标 🟡)。
多个 API 共享一个 upstream Service/Endpoints(指向宿主 docker0:9081 的 downstream)。
"""
from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

import yaml

from ..model import Route


class HigressSink:
    def __init__(self, cfg: dict):
        self.namespace = cfg.get("namespace", "higress-system")
        self.ingress_class = cfg.get("ingress_class", "higress")
        self.container = cfg.get("docker_container", "higress")
        self.data_dir = cfg.get("data_dir", "/data")
        self.kubeconfig = cfg.get("kubeconfig", "/tmp/higress-kubeconfig")
        self.channel = cfg.get("channel", "auto")
        self.upstream_name = "wso2-demo-downstream"
        self.upstream_port = int(cfg.get("upstream_port", 9081))
        self.host_ip = cfg.get("host_bridge_ip") or self._detect_docker0()

    # ---------- 渲染 ----------
    def _ingress(self, route: Route) -> dict:
        return {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "Ingress",
            "metadata": {
                "name": f"wso2-{route.name}",
                "namespace": self.namespace,
                "annotations": {"higress.io/backend-protocol": "HTTP"},
                "labels": {"managed-by": "wso2-adapter"},
            },
            "spec": {
                "ingressClassName": self.ingress_class,
                "rules": [{
                    "http": {
                        "paths": [{
                            "path": route.path,
                            "pathType": "Prefix",
                            "backend": {"service": {
                                "name": self.upstream_name,
                                "port": {"number": self.upstream_port},
                            }},
                        }]
                    }
                }],
            },
        }

    def _service(self) -> dict:
        return {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "name": self.upstream_name,
                "namespace": self.namespace,
                "labels": {"managed-by": "wso2-adapter"},
            },
            "spec": {
                "ports": [{"name": "http", "port": self.upstream_port,
                           "targetPort": self.upstream_port, "protocol": "TCP"}],
            },
        }

    def _endpoints(self) -> dict:
        return {
            "apiVersion": "v1",
            "kind": "Endpoints",
            "metadata": {
                "name": self.upstream_name,
                "namespace": self.namespace,
                "labels": {"managed-by": "wso2-adapter"},
            },
            "subsets": [{
                "addresses": [{"ip": self.host_ip}],
                "ports": [{"name": "http", "port": self.upstream_port, "protocol": "TCP"}],
            }],
        }

    # ---------- reconcile ----------
    def reconcile(self, desired: dict[str, Route]) -> dict:
        report = {"applied": [], "deleted": [], "host_ip": self.host_ip}
        Path(tempfile.mkdtemp(prefix="higress-")).mkdir(exist_ok=True)
        tmp = Path(tempfile.gettempdir()) / "wso2-higress-apply"
        for sub in ("ingresses", "services", "endpoints"):
            (tmp / sub).mkdir(parents=True, exist_ok=True)

        # 共享 service/endpoints(只要还有路由就写)
        if desired:
            (tmp / "services" / f"{self.upstream_name}.yaml").write_text(
                yaml.safe_dump(self._service(), sort_keys=False))
            (tmp / "endpoints" / f"{self.upstream_name}.yaml").write_text(
                yaml.safe_dump(self._endpoints(), sort_keys=False))

        desired_names = {f"wso2-{n}" for n in desired}
        for name, route in desired.items():
            (tmp / "ingresses" / f"wso2-{name}.yaml").write_text(
                "# AUTO-GENERATED by wso2-adapter\n"
                + yaml.safe_dump(self._ingress(route), sort_keys=False))
            report["applied"].append(f"wso2-{name}")

        channel = self._pick_channel()
        if channel == "dockercp":
            self._apply_dockercp(tmp)
        elif channel == "kubectl":
            self._apply_kubectl(tmp, desired_names)
        return report

    # ---------- 通道 ----------
    def _pick_channel(self) -> str:
        if self.channel in ("dockercp", "kubectl", "console"):
            return self.channel if self.channel != "console" else "dockercp"
        # auto: 容器在跑就用 dockercp
        if subprocess.run(["docker", "inspect", self.container],
                          capture_output=True).returncode == 0:
            return "dockercp"
        return "kubectl"

    def _apply_dockercp(self, tmp: Path) -> None:
        for sub in ("ingresses", "services", "endpoints"):
            src = tmp / sub
            if any(src.glob("*.yaml")):
                subprocess.run(["docker", "cp", f"{src}/.",
                                f"{self.container}:{self.data_dir}/{sub}/"],
                               check=True, capture_output=True)

    def _apply_kubectl(self, tmp: Path, desired: set[str]) -> None:
        for f in tmp.rglob("*.yaml"):
            subprocess.run(["kubectl", "--kubeconfig", self.kubeconfig,
                            "apply", "-f", str(f)], check=True)

    @staticmethod
    def _detect_docker0() -> str:
        r = subprocess.run(["ip", "-4", "addr", "show", "docker0"],
                           capture_output=True, text=True)
        for tok in r.stdout.split():
            if tok.count(".") == 3 and "/" in tok:
                return tok.split("/")[0]
        return "172.17.0.1"
